# permissions for end users to view spaces.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: space-viewer-role
rules:
- apiGroups:
  - k8s.suse.com
  resources:
  - spaces
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - k8s.suse.com
  resources:
  - spaces/status
  verbs:
  - get
